version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Update AWS CLI...
      #- pip3 install awscli --upgrade --user
  build:
    commands:
      - echo Build started on `date`
      #- export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain zyter --domain-owner 516804113156 --query authorizationToken --output text`
      #- export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain ${CODEARTIFACT_DOMAIN} --query authorizationToken --output text`
      - mvn -s settings.xml install
      #- mvn -s settings.xml clean package deploy
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn surefire-report:report #Running this task to execute unit tests and generate report.
      - mvn jacoco:report #Generating jacoco report
      - mvn test -f pom.xml -fn
cache:
  paths:
    - '/root/.m2/**/*'
reports: #New
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports
  jacoco-report:
    files:
      - '**/*' 
    base-directory: 'target/site/jacoco'
    file-format: 'JACOCOXML'
artifacts:
  files:
    - target/*
    - target/surefile-reports
    - target/site/jacoco
    - echo Artifacts uploading completed on `date`
    - /root/.m2/**/*
  # arn:aws:codebuild:ap-south-1:516804113156:report-group/test-report-group-code-coverage:
  #   files:
  #     - '**/*'
  #   #base-directory: 'target/simplecov-reports' # Location of the reports
  #   files:
  ##    - '**/*'
  #   file-format: 'SIMPLECOV'
